#!/bin/bash
cp $1 $1.bak || exit 1
declare lok=`locale -a | grep '^eo\>.*\.utf8'`
if [ -n $lok ]; then
# lok=eo.utf8
    export LC_ALL=$lok
    export LC_COLLATE=$lok
    export LC_CTYPE=$lok
    export LANG=eo
    locale
    date
    iconv -f LATIN3 -t UTF-8 $1.bak | sort -df | iconv -f UTF-8 -t LATIN3 > $1 || exit 3
    echo "ordigite laux $lok"
else
    export LC_CTYPE=C
    grep "zZ" $1 && exit 1
    sed -e 's/æ/czZ/g' -e 's/Æ/CzZ/g' \
        -e 's/ø/gzZ/g' -e 's/Ø/GzZ/g' \
        -e 's/¶/hzZ/g' -e 's/¦/HzZ/g' \
        -e 's/¼/jzZ/g' -e 's/¬/JzZ/g' \
        -e 's/þ/szZ/g' -e 's/Þ/SzZ/g' \
        -e 's/ý/uzZ/g' -e 's/Ý/UzZ/g' \
        -e 's/\(\\[^a-zA-Z]\)\([a-zA-Z]\)/\2zZ{\1}/g' \
        -e 's/\(\\[a-zA-Z]\){\([a-zA-Z]\)}/\2zZzZ{\1}/g' \
        -e 's/{\\\([a-zA-Z]\)\([a-zA-Z]*\)}/\1zZ{}{\2}/g' \
        $1 | sort -d -u > /tmp/temp && \
        sed -e 's/\([a-zA-Z]\)zZ{}{\([^}]*\)}/{\\\1\2}/g' \
        -e 's/\([a-zA-Z]\)zZzZ{\([^}]*\)}/\2{\1}/g' \
        -e 's/\([a-zA-Z]\)zZ{\([^}]*\)}/\2\1/g' \
        -e 's/czZ/æ/g' -e 's/CzZ/Æ/g' \
        -e 's/gzZ/ø/g' -e 's/GzZ/Ø/g' \
        -e 's/hzZ/¶/g' -e 's/HzZ/¦/g' \
        -e 's/jzZ/¼/g' -e 's/JzZ/¬/g' \
        -e 's/szZ/þ/g' -e 's/SzZ/Þ/g' \
        -e 's/uzZ/ý/g' -e 's/UzZ/Ý/g' /tmp/temp > $1 || exit 2
fi
wc -l $1.bak $1

# Local variables:
# coding: latin-3
# end:
